on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'index.html'
      - 'node/*'
      - 'script.js'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'index.html'
      - 'node/*'
      - 'script.js'

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Test
        run: |
          make -C node
          cp node/artifacts/fruit-english.js node/dist/
          cp node/artifacts/fruit-greek.js node/dist/
          cp node/artifacts/vegetable-english.js node/dist/
          cp node/artifacts/vegetable-greek.js node/dist/
      - name: commit changes
        run: |
          git add .
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git diff-index --quiet HEAD || git commit -m 'commit from github action'
          git push
